name: upgrade-gh-cli test

on:
  workflow_dispatch: {}
  pull_request: {}
  push:
    branches:
      - "main"
    paths:
      - ".github/workflows/composite/upgrade-gh-cli"
      - ".github/workflows/upgrade-gh-cli-test.yml"

jobs:
  upgrade-gh-cli-and-assert:
    name: Upgrade gh cli and assert-upgraded
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, ubuntu-18.04]
    steps:
      - name: Checkout composite actions repository
        uses: actions/checkout@v2
        with:
          repository: philip-gai/composite-actions
          path: composite-actions
          ref: ${{ github.ref }}
      - name: Upgrade gh cli and assert-upgraded
        uses: ./composite-actions/.github/workflows/composite/upgrade-gh-cli
        with:
          assert-upgraded: true

  upgrade-gh-cli-and-skip-assert:
    name: Upgrade gh cli and skip assertion
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, ubuntu-18.04]
    steps:
      - name: Checkout composite actions repository
        uses: actions/checkout@v2
        with:
          repository: philip-gai/composite-actions
          path: composite-actions
          ref: ${{ github.ref }}
      - name: Upgrade gh cli skip assert-upgraded
        uses: ./composite-actions/.github/workflows/composite/upgrade-gh-cli
        with:
          assert-upgraded: false
