name: upgrade-gh-cli test

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    paths:
      - ".github/workflows/composite/upgrade-gh-cli"

jobs:
  upgrade-gh-cli-test:
    name: Use upgrade gh cli latest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout composite actions repository
        uses: actions/checkout@v2
        with:
          repository: philip-gai/composite-actions
          path: composite-actions
          ref: ${{ github.ref }}
      - name: Upgrade gh cli and assert-upgraded
        uses: ./composite-actions/.github/workflows/composite/upgrade-gh-cli
        with:
          assert-upgraded: true
      - name: Upgrade gh cli skip assert-upgraded
        uses: ./composite-actions/.github/workflows/composite/upgrade-gh-cli
        with:
          assert-upgraded: false
